### ISSUE TITLE
POST ancillaries

### ISSUE THREAD

**Issue by Nosk14** [HBHackaton/api#2]
Get hotels between origin and destination

RQ
```
{
   lon, lat
   checkin: dd-MM-YYYY,
   checkout: dd-MM-YYYY
}
```

RS
```
{
    hotels: [ 
   {
      id, name. geolocation, description, address, photo, tags, 
      avail: [ {
                 date, time, price
                 }]
   }
   ],
    restaurants: [ 
   {
      id, name. geolocation, description, address, photo, tags, 
   }
   ]
}
```

**Comment by dFarras** [comment]
Una cosa, para obtener la imagen del hotel hay que hacer otra integración con content-api (la aplicación de info stática y hacer una búsqueda por el hotel del que queremos conocer la imagen)

Lo que consideréis

**Comment by pabloriutort** [comment]
Por ahora lo dejamos así y podemos tener una imagen de un hotel random en local y mostrar siempre esa. Por ejemplo: 

![](https://financialtribune.com/sites/default/files/field/image/november/16_horror.jpg)

La integración de content-api sería otro issue fuera del milestone de MVP, si quieres crear dicho issue _be my guest_
