### ISSUE TITLE
Design database for agenda

### ISSUE THREAD

**Issue by Nosk14** [HBHackaton/api#4]
User
- id
- nom

Agenda:
- Id
- nom
- id_user

Agenda_Event:
- id_agenda
- id_evento
- checkin
- checkout

Event:
- id
- name
- lon
- lat
- type: activity, hotel, restaurant
---
* Also create integration with core
* Keep in mind sqlite does not support datetimes

**Comment by pabloriutort** [comment]
@Nosk14 where do I put the schema.sql file?
